version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    command: -path=/migrations -database "postgres://user:password@db:5432/chatdb?sslmode=disable" up
    depends_on:
      - db
volumes:
  db-data: