version: '3.8'

services:
  donate-service:
    build: .
    ports:
      - '8082:8082'
    env_file:
      - .env
    depends_on:
      - db
    command: ['/wait-for-postgres.sh', '/app']

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: donate_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
